BreedingLogg/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BreedingLogg.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BreedingLogg/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;


namespace BreedingLogg.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BreedingLogg/Pages/Portada.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BreedingLogg.Pages
{
    public class PortadaModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BreedingLogg/Pages/Presentación.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace BreedingLogg.Pages
{
    public class PresentaciónModel : PageModel
    {
        public void OnGet()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {

            }
            else
            {
                HttpContext.Session.Clear();
            }
        }

        public void OnPostUsuarios()
        {
            Response.Redirect("LoginUsuarios");
        }

        public void OnPostCriadores()
        {
            Response.Redirect("LoginCriadores");
        }
    }
}

BreedingLogg/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BreedingLogg.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BreedingLogg/Pages/QuienesSomos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BreedingLogg.Pages
{
    public class QuienesSomosModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BreedingLogg/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">¡Bienvenido!</h1>
    <p>A VeteriSystems tu sistema de consulta de crianza de confianza.</p>

</div>

&nbsp;

<div class="containerHome">
    <div class="Grid1">
        <div>
            <div>
                <br />
                <br />
                <h1 class="display-2">¿Te gusta la Crianza?</h1>
                <h1 class="display-6">¿Buscas el mejor Pedegree?</h1>
                <style>
                    .display-2 {
                        color: whitesmoke;
                        text-align: center;
                    }

                    .display-6 {
                        color: whitesmoke;
                        text-align: center;
                    }
                </style>
            </div>
            <br />

            <!--Divicion-->
            <hr class="divider">

            <div>
                <br />
                <h6 class="textoLogin">

                    Nosotros te ofrecemos el mejor catálogo y los mejores Ejemplares para que tu Crianza sea la mejor experiencia

                </h6>

                <h6 class="textoLogin">
                    <br />
                    Solo, ¡LO MEJOR DE LO MEJOR!

                </h6>
                <style>
                    .textoLogin {
                        color: white;
                        text-align: center;
                    }
                </style>
                <br />
                <br />

                <!--BTN PORTADA-->
                <div class="CentrarBtn">
                    <a href="Presentación" class=" colorBtn btn btn-primary btn-lg" tabindex="-1" role="button">Ingresar</a>
                </div>

                <h6 class="textoLogin">
                    <br />
                    <br />
                    Registrate y comienza a explorar en un mundo lleno de los mejores Ejemplares con el mejor Pedegree

                </h6>
            </div>
        </div>
    </div>

    <div class="Grid2">
        <style>
            .Grid2 {
                background-color: #f4623a;
            }
        </style>
        <br />
        <h6 class="textoLogin">
            <br />
            ¿Buscas un perro en particular?

        </h6>
        <br />
        <h6 class="textoLogin">
            <br />

            Explora y conoce todas magníficas razas caninas

        </h6>
        <br />

        <h1 class="display-6"><strong>SOMOS TU MEJOR OPCIÓN</strong></h1>
        <!--Divicion-->
        <hr class="divider-light">
        <br />
        <h6 class="textoLogin">
            La mejor Crianza, los mejores Ejemplares, los mejores Criadores y
            el mejor Pedegree al alcance de tu mano
        </h6>
    </div>


    <!--TARJETAS-->

    <div class="Cards align-items-center">

        <br />

        <!--EJEMPLARES-->
        <div class="item  card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/img/EJEMPLARES_MUESTRA.jpg" alt="..." height="230" width="230">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="font-weight-bold card-title">EJEMPLARES</h5>
                        <p class="card-text">

                            Consulta nuestro catálogo y enamórate de nuestros ejemplares mas hermosos,
                            finos y de buen pedigree.

                        </p>

                    </div>
                    <a asp-page="/EjemplaresMachos/Index" class="btn btn-primary">Consultar / Machos</a>
                    <a asp-page="/EjemplaresHembras/Index" class="hembra btn btn-primary">Consultar / Hembras</a>
                    <style>
                        .hembra {
                            background-color: #CA3ACC;
                            border-color: #CA3ACC;
                        }

                    </style>
                </div>
            </div>
        </div>

        <!--CRIADORES-->
        <div class="item  card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/img/CRIADORES_MUESTRA.jpeg" alt="..." height="230" width="230">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="font-weight-bold card-title">CRIADORES</h5>
                        <p class="card-text">

                            Consulta el perfil y toda la información de nuestros criadores, contactalos y visita
                            los ejemplares de tu agrado.

                        </p>

                    </div>
                    <a href="Presentación" class="btn btn-primary">Acceder</a>
                </div>
            </div>
        </div>

        <!--CRUZA-->
        <div class="item  card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/img/CRUZA_MUESTRA.jpg" alt="..." height="230" width="230">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="font-weight-bold card-title">CRUZAS</h5>
                        <p class="card-text">

                            Consulta la información de los ejemplares actuales que se encuentren en proceso de cruza,
                            fechas de emparejamientos y fechas previstas de nacimiento. Así como datos de los padres, etc.

                        </p>

                    </div>
                    <a href="/Cruces/Index" class="btn btn-primary">Consultar</a>
                </div>
            </div>
        </div>

        <!--ARBOL-->
        <div class="item  card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="/img/Arbol_Muestra.jpg" alt="..." height="230" width="230">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="font-weight-bold card-title">GENEALOGIA</h5>
                        <p class="card-text">

                            Consulta toda la información acerca de los antepasados y predecesores de las Ejemplares, analiza toda sus rama genealógica
                            y decide cual será tu mejor opción.


                        </p>
                        <!--<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>-->
                    </div>
                    <a href="/Cruces/Index" class="btn btn-primary">Consultar</a>
                </div>
            </div>
        </div>


    </div>

</div>

BreedingLogg/Pages/LoginCriadores.cshtml
@page
@model BreedingLogg.Pages.LoginModel
@{
}

<div class="text-center">
    <h1 class="display-4">ACCESO A CRIADORES</h1>
    <p>VeteriSystems tu sistema de consulta de crianza de confianza.</p>
    <br />
    <br />
    <br />
    <br />

</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!--Formulario-->
            <div class="FormLogin">
                <form method="post">

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Usuario:</label>
                        <input class="form-control" type="text" asp-for="usuario" aria-describedby="userHelp" required />
                        <div class="invalid-feedback">
                            Debes ingresar el Nombre de Usuario del Criador
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                        <input class="form-control" type="password" asp-for="contrasena" required />
                        <div class="invalid-feedback">
                            Debes ingresar la Contraseña
                        </div>
                    </div>

                    <div class="modal-footer"></div>
                    <div>
                        <button class="btn btn-primary" type="submit">Iniciar Sesión</button>
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                </form>
            </div>
        </div>
    </div>
</div>

BreedingLogg/Pages/LoginUsuarios.cshtml
@page
@model BreedingLogg.Pages.LoginUsuariosModel
@{
}

<div class="text-center">
    <h1 class="display-4">ACCESO A ADMINISTRADORES</h1>
    <p>VeteriSystems tu sistema de consulta de crianza de confianza.</p>
    <br />
    <br />
    <br />
    <br />

</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!--Formulario-->
            <div class="FormLogin">
                <form method="post">

                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Usuario:</label>
                        <input class="form-control" type="text" asp-for="usuario" aria-describedby="userHelp" required />
                        <div class="invalid-feedback">
                            Debes ingresar el Nombre de Usuario del Criador
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Contraseña</label>
                        <input class="form-control" type="password" asp-for="contrasena" required />
                        <div class="invalid-feedback">
                            Debes ingresar la Contraseña
                        </div>
                    </div>

                    <div class="modal-footer">
                        <div class="CentrarBtn">
                            <button class="ColorBotones btn btn-primary" type="submit">Iniciar Sesión</button>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                </form>
            </div>
        </div>
    </div>
</div>

BreedingLogg/Pages/Portada.cshtml
@page
@model BreedingLogg.Pages.PortadaModel
@{
}

<div class="backgroundPortada">
    <div class="container">

        <div class="row align-items-start">

            <div class="col">
                &nbsp;
                <h1 class="text-white text-center">UNIVERSIDAD TECNOLOGICA METROPOLITANA</h1>
                &nbsp;
            </div>

        </div>

        <div class="row align-items-center">

            <div class="col">
                <h2 class="text-center text-white">Oscar Josue Uh Perez</h2>
            </div>

        </div>

        <div class="row align-items-center">

            <div class="col">
                <h3 class="text-center text-white">Aplicaciones Web</h3>
            </div>

        </div>

        <div class="row align-items-center">

            <div class="col">
                <h3 class="text-center text-white">3°B</h3>
                <h3 class="text-center text-white">Parcial 3</h3>
            </div>

        </div>

        <div class="row align-items-center">

            <div class="col">
                <h2 class="text-white text-center">Proyecto - Breeding Log</h2>
            </div>

        </div>

        <div class="container text-center">
            <div class="row align-items-center">

                <div class="col">
                    <div class="container text-center">
                        <img src="https://www.utmetropolitana.edu.mx/Publicaciones/recursos/BotonImagen/logo%20UTM%20blanco-01%20copia.png" width="500" style="opacity:80%;" />
                    </div>
                </div>

            </div>
        </div>

        <div class="row align-items-end">

            <div class="col">
                <div class="item card text-center bg-dark text-white">

                    <div class="card-header text-muted">
                        Desarrollo de Software Multiplataforma
                    </div>

                    <div class="card-body bg-dark text-white">
                        <h6 class="card-title font-weight-bold">INTEGRANTES</h6>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item list-group-item-dark">Carlos M Mezquita Alvarado / Graphic designer</li>
                            <li class="list-group-item list-group-item-dark">Fabian F Aguilar Rivero / Assistance and support</li>
                            <li class="list-group-item list-group-item-dark">Javier A Sulub Flores / Develoteca Lover</li>
                        </ul>

                    </div>

                    <div class="card-footer text-muted">
                        Luchando por su calificación
                    </div>

                </div>
            </div>

        </div>

        <div>
            &nbsp;
            &nbsp;
        </div>

        <div class="container text-center">
            <div class="row align-items-end">
                <div class="col">
                    <a href="Presentación">EMPEZAR</a>
                </div>
            </div>
        </div>

    </div>
</div>

BreedingLogg/Pages/Presentación.cshtml
@page
@model BreedingLogg.Pages.PresentaciónModel
@{
}

<div class="containerLogin">
    <div class="background"></div>
    <div class="FormLogin text-center">
        <style>
            .ColorBotones {
                background: #76448A !important;
                border-color: #76448A !important;
            }
        </style>

        <div>
            <h1 class="display-2"><strong>¿Ya tienes una cuenta?</strong></h1>
            <style>
                .display-2 {
                    color: whitesmoke;
                }
            </style>
        </div>

        <div>

            <h6 class="textoLogin">

                Inicia Sesión y disfruta las ventajas de ser un socio VET.

            </h6>
            <br />
            <style>
                .textoLogin {
                    color: white;
                }
            </style>
        </div>
        
        <div class="AlinearBotones">

            <h6 class="textoLogin"> Selecciona un Perfil de Acceso</h6>

            <form method="post">

                <input type="submit" class="ColorBotones btn btn-primary" value="Administrador" asp-page-handler="Usuarios" />

                <input type="submit" class="ColorBotones btn btn-primary" value="Criador" asp-page-handler="Criadores" />

            </form>

        </div>

    </div>

</div>

BreedingLogg/Pages/QuienesSomos.cshtml
@page
@model BreedingLogg.Pages.QuienesSomosModel
@{
}

<div class="text-center">
    <h2 class="display-4">¿Quienes Somos?</h2>
</div>

<div>
    &nbsp;
    &nbsp;
</div>

<div class="row">
    <div class="col-4">
        <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Carlos Mezquita</a>
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Fabian Rivero</a>
            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Javier Sulub</a>
        </div>
    </div>

    <div class="col-8">

        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">

                <div class="card mb-3" style="width:500px;">
                    <img class="card-img-top" src="https://scontent.fcjs3-1.fna.fbcdn.net/v/t1.6435-9/31229303_2046804025582395_3490063929076350976_n.jpg?_nc_cat=110&ccb=1-3&_nc_sid=174925&_nc_eui2=AeFfKzLSXzb3j9IwffI0nvOn1m2cWNdcZtrWbZxY11xm2teiDmrUH3zmwhvew5h9nkOlKpvS32K46wS3Z-FS6Q-u&_nc_ohc=4NPC0q1ZJLcAX_eqN82&_nc_ht=scontent.fcjs3-1.fna&oh=acfe929a073bf77a28a5dd3e59cb3202&oe=6124F089" alt="Card image cap">

                    <div class="card-body">

                        <h5 class="card-title text-muted">Carlos M Mezquita Alvarado</h5>
                        <h6 class="card-title">Estudiante / Desarrollo de Software Multiplataforma</h6>
                        <div class="dropdown-divider"></div>

                        <div style="text-align:justify">
                            <p class="card-text">
                                <i>
                                    Soy Carlos Mezquita, Nací el 04/Noviembre/1994 (26 años) Estudio en la Universidad Tecnológica Metropolitana UTM
                                    la carrera de DSM Desarrollo de Software Multiplataforma, me encanta la computación, desarrollo de videojuegos,
                                    Diseño grafico y todo lo relacionado. Mi plan a futuro es recibirme en la Ingenieria e involucrarme a fondo acerca
                                    del desarrollo de videojuegos.
                                </i>
                            </p>
                        </div>

                    </div>

                    <div class="card-footer text-muted">
                        <small class="font-weight-bold">De:</small>
                        <h6>Ciudad de México</h6>
                        <div class="dropdown-divider"></div>
                        <small class="font-weight-bold">Vive en:</small>
                        <h6>Mérida, Yucatán</h6>

                    </div>

                </div>
            </div>

            <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                <div class="card mb-3" style="width:500px;">
                    <img class="card-img-top" src="/img/Papucho.jpeg" alt="Card image cap">

                    <div class="card-body">

                        <h5 class="card-title text-muted">Fabian F Aguilar Rivero</h5>
                        <h6 class="card-title">Estudiante / Desarrollo de Software Multiplataforma</h6>
                        <div class="dropdown-divider"></div>

                        <div style="text-align:justify">
                            <p class="card-text">
                                <i>
                                    Me llamo Fabian Francisco Aguilar Rivero, nací en Mérida, Yucatán el 15 de septiembre del 2002,
                                    actualmente vivo en el estado de yucatán, tengo 18 años, me encuentro estudiando en la Universidad
                                    Tecnológica Metropolitana en Desarrollo de Software Multiplataforma (DSM).
                                </i>
                            </p>
                        </div>

                    </div>

                    <div class="card-footer text-muted">
                        <small class="font-weight-bold">De:</small>
                        <h6>Mérida, Yucatán</h6>
                        <div class="dropdown-divider"></div>
                        <small class="font-weight-bold">Vive en:</small>
                        <h6>Mérida, Yucatán</h6>

                    </div>

                </div>
            </div>

            <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">
                <div class="card mb-3" style="width:500px;">
                    <img class="card-img-top" src="/img/Javo.jpeg" alt="Card image cap">

                    <div class="card-body">

                        <h5 class="card-title text-muted">Javier A Sulub Flores</h5>
                        <h6 class="card-title">Estudiante / Desarrollo de Software Multiplataforma</h6>
                        <div class="dropdown-divider"></div>

                        <div style="text-align:justify">
                            <p class="card-text">
                                <i>
                                    Javier Alexander Sulub Flores nació el 17 de mayo de 2002 en el Hospital T1, Mérida Yucatán, aproximadamente a las 8:30 de la mañana; sus padres son Rodrigo Ventura Sulub Ramos y Rosalinda Santos Flores Osgaya
                                    En la prepa aprendió muchas cosas nuevas, ahí tomo muchas decisiones que cambiaron su vida, en esto influyó la gente con la que se juntaba y sus compañeros, no influyó hacia algo malo, pero si para cambiar. Ahora se encuentra cursando la universidad y afortunadamente no a reprobado ni una sola materia a lo largo de su vida, no es de los mejores, pero se mantiene bien y estable.
                                </i>
                            </p>
                        </div>

                    </div>

                    <div class="card-footer text-muted">
                        <small class="font-weight-bold">De:</small>
                        <h6>Mérida, Yucatán</h6>
                        <div class="dropdown-divider"></div>
                        <small class="font-weight-bold">Vive en:</small>
                        <h6>Mérida, Yucatán</h6>

                    </div>

                </div>
            </div>

        </div>

    </div>

</div>

BreedingLogg/Pages/cerrarsesion.cshtml
@page
@model BreedingLogg.Pages.cerrarsesionModel
@{
}

<div>
    &nbsp;
    &nbsp;
    &nbsp;
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">

        <div class="card">

            <div class="card-header text-center font-weight-bold">
                CERRANDO SESIÓN
            </div>

            <img class="card-img-top" src="/img/crying-cat.jpg" alt="Card image cap">

            <div class="card-body">

                <h5 class="card-title">¿Estas seguro?</h5>

            </div>

            <div class="text-center">
                <div class="card-footer">

                    <form method="post">
                        <input type="submit" value="Si" class="btn btn-danger" asp-page-handler="Cerrar" />

                        <input type="submit" value="No" class="btn btn-primary" asp-page-handler="Cancelar" />
                    </form>

                </div>
            </div>

        </div>

    </div>
</div>